# Book settings
title: Jupyter Guide to Linear Algebra
author: Ben Vanderlei
logo: reflection_logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/bvanderlei/jupyter-guide-to-linear-algebra
  branch: main

launch_buttons:
  notebook_interface: "classic"
  colab_url: ""
  thebe: true
  
html:
  extra_footer:
    <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Jupyter Guide to Linear Algebra</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.
    
sphinx:
  config:
    html_show_copyright: false